version: '3.8'
# Microservice application stack
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  users-api:
    build: ./users-api
    ports:
      - "9081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_PORT=8081
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  auth-api:
    build: ./auth-api
    ports:
      - "9080:8080"
    environment:
      - AUTH_API_PORT=8080
      - USERS_API_ADDRESS=http://users-api:8081
      - JWT_SECRET=myfancysecret
    depends_on:
      - users-api

  todos-api:
    build: ./todos-api
    ports:
      - "9082:8082"
    environment:
      - TODO_API_PORT=8082
      - JWT_SECRET=foo
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis
      - auth-api

  log-message-processor:
    build: ./log-message-processor
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "9083:80"
    environment:
      - VUE_APP_API_URL=http://todos-api:8082
    depends_on:
      - todos-api
